In [1]:
import sys
project_root = "/home/velocitatem/Documents/Projects/PHANTOM/experiments"
from pathlib import Path
if str(Path.cwd().parent if 'notebooks' in str(Path.cwd()) else Path.cwd()) not in sys.path:
  sys.path.insert(0, str(project_root))

In [2]:
from procesing.steps import (
    ExtractSessionFeaturesStep,
    _extract_features_for_session,
    FetchInteractionsStep,
)
from procesing.context import PipelineContext
from procesing.providers import SupabaseProvider, BackendAPIProvider

In [3]:
class Provider(SupabaseProvider, BackendAPIProvider):
    def __init__(self, backend_url: str):
        SupabaseProvider.__init__(self)
        BackendAPIProvider.__init__(self, backend_url=backend_url)
# example run
context = PipelineContext(
    provider=Provider(backend_url="http://localhost:5000"),
    store_mode='hotel',
    window_size='5min',

)

In [4]:
df=FetchInteractionsStep(context).transform(None)
df.head()

,sessionId,experimentId,eventName,page,productId,storeMode,userAgent,ts,metadata_referrer,metadata_elementText,metadata_dateIndex,metadata_dwellTime,metadata_type,metadata_roomType,metadata_price,metadata_nights,metadata_total,metadata_itemCount,dateIndex
0,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,None,page_view,/,None,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25T20:20:13.061Z,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
1,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,None,hover_over_title,/hotel/products,d018efc1-25e9-4284-b276-80386e048b25,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25T20:21:17.425Z,NaN,Junior Suite,1.0,1200.0,NaN,NaN,NaN,NaN,NaN,NaN,1
2,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,None,hover_over_paragraph,/hotel/products,d018efc1-25e9-4284-b276-80386e048b25,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25T20:21:19.496Z,NaN,price,1.0,1202.0,NaN,NaN,NaN,NaN,NaN,NaN,1
3,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,None,page_view,/hotel/products/d018efc1-25e9-4284-b276-80386e...,None,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25T20:21:21.922Z,http://localhost:3000/hotel/products?dateIndex...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
4,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,None,learn_more_about_item,/hotel/products/d018efc1-25e9-4284-b276-80386e...,d018efc1-25e9-4284-b276-80386e048b25,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25T20:21:22.674Z,NaN,NaN,1.0,NaN,hotel,Junior Suite,NaN,NaN,NaN,NaN,1

In [5]:
df['sessionId'].unique()

array(['d423ce8a-77aa-4c9a-94d4-d1adddcc3472',
       'fba26fde-4c50-4545-9734-ff415ac2d791',
       'e48ae739-dff8-4e56-b9b9-efff9de55a48',
       '3d0fed38-45fd-4d44-8511-d157adacb238',
       'c404dbe5-116f-42c0-b199-503516dbbe91'], dtype=object)

In [6]:
df['sessionId'].value_counts()

sessionId
d423ce8a-77aa-4c9a-94d4-d1adddcc3472    50
c404dbe5-116f-42c0-b199-503516dbbe91    18
e48ae739-dff8-4e56-b9b9-efff9de55a48     8
fba26fde-4c50-4545-9734-ff415ac2d791     2
3d0fed38-45fd-4d44-8511-d157adacb238     2
Name: count, dtype: int64

In [7]:
session="d423ce8a-77aa-4c9a-94d4-d1adddcc3472"
df=df[df['sessionId'] == session]
df=df.dropna(subset=["experimentId"])
df.head()

,sessionId,experimentId,eventName,page,productId,storeMode,userAgent,ts,metadata_referrer,metadata_elementText,metadata_dateIndex,metadata_dwellTime,metadata_type,metadata_roomType,metadata_price,metadata_nights,metadata_total,metadata_itemCount,dateIndex
30,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,hover_over_title,/hotel/products,d018efc1-25e9-4284-b276-80386e048b25,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25T21:05:43.942Z,NaN,Junior Suite,1.0,1252.0,NaN,NaN,NaN,NaN,NaN,NaN,1
31,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,page_view,/hotel/products/d018efc1-25e9-4284-b276-80386e...,None,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25T21:05:45.407Z,http://localhost:3000/hotel/products?dateIndex...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
32,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,learn_more_about_item,/hotel/products/d018efc1-25e9-4284-b276-80386e...,d018efc1-25e9-4284-b276-80386e048b25,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25T21:05:45.515Z,NaN,NaN,1.0,NaN,hotel,Junior Suite,NaN,NaN,NaN,NaN,1
33,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,page_view,/hotel/products,None,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25T21:05:50.176Z,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
34,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,page_view,/hotel/products/2ddabbfc-4127-48fc-86dc-ebc4c6...,None,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25T21:05:54.666Z,http://localhost:3000/hotel/products?dateIndex...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>

In [11]:
from procesing.steps import ExtractSessionFeaturesStep
feats = ExtractSessionFeaturesStep(context).transform(df)

In [12]:
feats

,sessionId,experimentId,eventName,page,productId,storeMode,userAgent,ts,metadata_referrer,metadata_elementText,...,searches,cart_adds,hovers,unique_products_viewed,product_view_depth,session_duration_sec,interaction_velocity,avg_time_between_events,std_time_between_events,cart_to_view_ratio
0,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,hover_over_title,/hotel/products,d018efc1-25e9-4284-b276-80386e048b25,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25 21:05:43.942000+00:00,NaN,Junior Suite,...,0.0,0.0,1.0,1.0,1.0,0.000,0.000000,0.000000,0.000000,0.0
1,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,page_view,/hotel/products/d018efc1-25e9-4284-b276-80386e...,None,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25 21:05:45.407000+00:00,http://localhost:3000/hotel/products?dateIndex...,NaN,...,0.0,0.0,1.0,1.0,1.0,1.465,81.911263,1.465000,NaN,0.0
2,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,learn_more_about_item,/hotel/products/d018efc1-25e9-4284-b276-80386e...,d018efc1-25e9-4284-b276-80386e048b25,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25 21:05:45.515000+00:00,NaN,NaN,...,0.0,0.0,1.0,1.0,2.0,1.573,114.431024,0.786500,0.959544,0.0
3,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,page_view,/hotel/products,None,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25 21:05:50.176000+00:00,,NaN,...,0.0,0.0,1.0,1.0,2.0,6.234,38.498556,2.078000,2.337580,0.0
4,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,page_view,/hotel/products/2ddabbfc-4127-48fc-86dc-ebc4c6...,None,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25 21:05:54.666000+00:00,http://localhost:3000/hotel/products?dateIndex...,NaN,...,0.0,0.0,1.0,1.0,2.0,10.724,27.974636,2.681000,2.257718,0.0
5,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,learn_more_about_item,/hotel/products/2ddabbfc-4127-48fc-86dc-ebc4c6...,2ddabbfc-4127-48fc-86dc-ebc4c677efa2,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25 21:05:54.794000+00:00,NaN,NaN,...,0.0,0.0,1.0,2.0,2.0,10.852,33.173609,2.170400,2.264184,0.0
6,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,page_view,/hotel/products,None,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25 21:05:57.670000+00:00,,NaN,...,0.0,0.0,1.0,2.0,2.0,13.728,30.594406,2.288000,2.045532,0.0
7,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,page_view,/hotel/products/2cd7f756-fc65-4ba0-ab01-74521c...,None,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25 21:06:03.130000+00:00,http://localhost:3000/hotel/products?dateIndex...,NaN,...,0.0,0.0,1.0,2.0,2.0,19.188,25.015635,2.741143,2.219055,0.0
8,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,learn_more_about_item,/hotel/products/2cd7f756-fc65-4ba0-ab01-74521c...,2cd7f756-fc65-4ba0-ab01-74521c1fff43,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25 21:06:03.253000+00:00,NaN,NaN,...,0.0,0.0,1.0,3.0,2.0,19.311,27.963337,2.413875,2.253349,0.0
9,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,add_item_to_cart,/hotel/products/2cd7f756-fc65-4ba0-ab01-74521c...,2cd7f756-fc65-4ba0-ab01-74521c1fff43,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25 21:06:06.815000+00:00,NaN,NaN,...,0.0,1.0,1.0,3.0,2.0,22.873,26.231802,2.541444,2.142276,0.0
10,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,page_view,/hotel/products,None,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25 21:06:08.600000+00:00,,NaN,...,0.0,1.0,1.0,3.0,2.0,24.658,26.766161,2.465800,2.033873,0.0
11,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,checkout_start,/cart,None,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25 21:06:11.586000+00:00,NaN,NaN,...,0.0,1.0,1.0,3.0,2.0,27.644,26.045435,2.513091,1.935866,0.0
12,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,hover_over_title,/hotel/products,7f71fbe2-343c-4a46-94ea-07cbd903a86c,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25 21:06:28.050000+00:00,NaN,Executive Suite,...,0.0,1.0,2.0,4.0,2.0,44.108,17.683867,3.675667,4.430110,0.0
13,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,hover_over_paragraph,/hotel/products,7f71fbe2-343c-4a46-94ea-07cbd903a86c,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25 21:06:31.806000+00:00,NaN,price,...,0.0,1.0,3.0,4.0,2.0,47.864,17.549724,3.681846,4.241566,0.0
14,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,page_view,/hotel/products/7f71fbe2-343c-4a46-94ea-07cbd9...,None,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25 21:06:33.847000+00:00,http://localhost:3000/hotel/products?dateIndex...,NaN,...,0.0,1.0,3.0,4.0,2.0,49.905,18.034265,3.564643,4.098693,0.0
15,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,learn_more_about_item,/hotel/products/7f71fbe2-343c-4a46-94ea-07cbd9...,7f71fbe2-343c-4a46-94ea-07cbd903a86c,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25 21:06:34.029000+00:00,NaN,NaN,...,0.0,1.0,3.0,4.0,3.0,50.087,19.166650,3.339133,4.045016,0.0
16,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,page_view,/hotel/products,None,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25 21:06:37.255000+00:00,,NaN,...,0.0,1.0,3.0,4.0,3.0,53.313,19.132294,3.332063,3.907959,0.0
17,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,hover_over_title,/hotel/products,7f71fbe2-343c-4a46-94ea-07cbd903a86c,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25 21:06:43.694000+00:00,NaN,Executive Suite,...,0.0,1.0,4.0,4.0,4.0,59.752,18.074709,3.514824,3.858168,0.0
18,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,page_view,/hotel/products/7f71fbe2-343c-4a46-94ea-07cbd9...,None,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25 21:06:44.387000+00:00,http://localhost:3000/hotel/products?dateIndex...,NaN,...,0.0,1.0,4.0,4.0,4.0,60.445,18.860121,3.358056,3.801607,0.0
19,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,learn_more_about_item,/hotel/products/7f71fbe2-343c-4a46-94ea-07cbd9...,7f71fbe2-343c-4a46-94ea-07cbd903a86c,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25 21:06:44.492000+00:00,NaN,NaN,...,0.0,1.0,4.0,4.0,5.0,60.550,19.818332,3.186842,3.769122,0.0
20,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,add_item_to_cart,/hotel/products/7f71fbe2-343c-4a46-94ea-07cbd9...,7f71fbe2-343c-4a46-94ea-07cbd903a86c,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25 21:06:46.279000+00:00,NaN,NaN,...,0.0,2.0,4.0,4.0,6.0,62.337,20.212715,3.116850,3.681924,0.0
21,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,checkout_start,/cart,None,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-25 21:06:48.275000+00:00,NaN,NaN,...,0.0,2.0,4.0,4.0,6.0,64.333,20.518241,3.063476,3.597021,0.0
22,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,page_view,/,None,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-28 18:26:19.145000+00:00,,NaN,...,0.0,2.0,4.0,4.0,6.0,64.333,21.450888,11347.054682,53208.035246,0.0
23,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,hover_over_title,/hotel/products,d018efc1-25e9-4284-b276-80386e048b25,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-28 18:27:27.527000+00:00,NaN,Junior Suite,...,0.0,2.0,5.0,4.0,6.0,132.715,10.850318,10856.677609,52037.867752,0.0
24,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,page_view,/hotel/products,None,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-28 18:30:23.429000+00:00,,NaN,...,0.0,2.0,5.0,4.0,6.0,308.617,4.860393,10411.645292,50940.715176,0.0
25,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,page_view,/hotel/products,None,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-28 18:34:12.526000+00:00,,NaN,...,0.0,2.0,5.0,4.0,6.0,537.714,2.901171,10004.343360,49909.724987,0.0
26,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,page_view,/hotel/products,None,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-28 18:34:42.426000+00:00,,NaN,...,0.0,2.0,5.0,4.0,6.0,567.614,2.854052,9620.710923,48940.453026,0.0
27,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,page_view,/hotel/products,None,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-28 18:39:39.397000+00:00,,NaN,...,0.0,2.0,5.0,4.0,6.0,864.585,1.943129,9275.387222,48023.596355,0.0
28,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,page_view,/hotel/products,None,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-28 18:40:49.203000+00:00,,NaN,...,0.0,2.0,5.0,4.0,6.0,934.391,1.862175,8946.616464,47157.980032,0.0
29,d423ce8a-77aa-4c9a-94d4-d1adddcc3472,53aefd07-f66a-4d7f-ba8b-7ea1fc562d35,page_view,/admin/experiments,None,hotel,Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Geck...,2025-11-29 17:27:43.775000+00:00,,NaN,...,0.0,2.0,5.0,4.0,6.0,934.391,1.926388,11466.201138,48255.070941,0.0